---
# defaults file for ansible-role-nomad
nomad_version: 0.7.1
nomad_sha256sum: 72b32799c2128ed9d2bb6cbf00c7600644a8d06c521a320e42d5493a5d8a789a
nomad_force_install: False

nomad_client: true
nomad_server: false
nomad_telemetry: false

nomad_iface: eth0

nomad_region: "global"
nomad_datacenter: "dc1"
nomad_name: ''
nomad_log_level: "INFO"
nomad_bind_addr: "{{ hostvars[inventory_hostname]['ansible_'+nomad_iface]['ipv4']['address'] }}"
nomad_enable_debug: false
nomad_ports_http: 4646
nomad_ports_rpc: 4647
nomad_ports_serf: 4648
nomad_addresses_http: "{{ nomad_bind_addr }}"
nomad_addresses_rpc: "{{ nomad_bind_addr }}"
nomad_addresses_serf: "{{ nomad_bind_addr }}"
nomad_advertise_rpc: "{{ nomad_bind_addr }}"
nomad_advertise_serf: "{{ nomad_bind_addr }}"
nomad_leave_on_interrupt: false
nomad_leave_on_terminate: false
nomad_enable_syslog: false
nomad_syslog_facility: "LOCAL0"
nomad_disable_update_check: false
nomad_disable_anonymous_signature: false

nomad_telemetry_statsite_address: ''
nomad_telemetry_statsd_address: ''
nomad_telemetry_disable_hostname: false

nomad_server_bootstrap_expect: 3
nomad_server_data_dir: "{{ nomad_data_dir }}/server"
nomad_server_protocol_version: ''
nomad_server_num_schedulers: "{{ ansible_processor_cores }}"
nomad_server_enabled_schedulers: []
nomad_server_node_gc_threshold: ''
nomad_server_rejoin_after_leave: ''
nomad_server_retry_join: []
nomad_server_retry_interval: 30s
nomad_server_retry_max: 0
nomad_server_start_join: []

nomad_client_state_dir: "{{ nomad_data_dir }}/client"
nomad_client_alloc_dir: "{{ nomad_data_dir }}/alloc"
nomad_client_servers: []
nomad_client_node_id: ''
nomad_client_node_class: ''
nomad_client_meta: {}

nomad_tls_enable: False
nomad_tls_src_dir: "{{ lookup('env','NOMAD_SRC_FILES') | default(role_path+'/files', true) }}"
nomad_tls_dest_dir: "{{ lookup('env','NOMAD_TLS_DEST_DIR') | default('/etc/nomad/ssl', true) }}"
nomad_tls_http: True
nomad_tls_rpc: True
nomad_tls_verify_server_hostname: False
nomad_tls_verify_client: False

nomad_vault: False
nomad_vault_address: https://active.vault.service.consul:8200
nomad_vault_create_from_role: nomad-cluster
