---
fabio_version: 1.5.6
fabio_go_version: 1.9.2
fabio_checksum_file: "fabio-go{{ fabio_go_version }}-{{ fabio_version }}.sha256"
fabio_checksum_file_url: "https://github.com/eBay/fabio/releases/download/v{{ fabio_version }}/{{ fabio_checksum_file }}"
fabio_pkg: "fabio-{{ fabio_version }}-go{{ fabio_go_version }}-linux_amd64"
fabio_pkg_url: "https://github.com/eBay/fabio/releases/download/v{{ fabio_version }}/fabio-{{ fabio_version }}-go{{ fabio_go_version }}-linux_amd64"
fabio_directories_config: /etc/fabio.d
fabio_download_dir: /usr/local/src/fabio-release

fabio_validate_certs: true
fabio_verify_checksum_signature: True
    
fabio_signature_file: "{{ fabio_checksum_file }}.sig"
fabio_signature_url: "https://github.com/eBay/fabio/releases/download/v{{ fabio_version }}/{{ fabio_signature_file }}"

fabio_properties_proxy_addr: ":80"

fabio_binary_path: /usr/bin
fabio_configure: true
fabio_create_directories: true
fabio_create_user: false
fabio_directories_install: /usr/local/src/fabio
fabio_directories_log: /var/log/fabio
fabio_go_checksum: "1862f4c3d3907e59b04a757cfda0ea7aa9ef39274af99a784f5be843c80c6772"
fabio_go_pkg: "go{{ fabio_go_version }}.linux-amd64.tar.gz"
fabio_home_dir: /opt/fabio
fabio_install_from_source: false
fabio_manage_service: true
fabio_properties_additional: {}
fabio_symlink: false

# TLS
fabio_tls_src_dir: /home/vagrant/pki
fabio_tls_dest_dir: "{{ fabio_directories_config }}/ssl"
fabio_tls_ca_cert: "ca.pem"
fabio_tls_server_cert: "fabio.service.consul.pem"
fabio_tls_server_key: "fabio.service.consul-key.pem"
fabio_tls_key_material:
- { src: "{{ fabio_tls_src_dir}}/{{ fabio_tls_ca_cert }}", dest: "{{ fabio_tls_dest_dir }}/{{ fabio_tls_ca_cert }}" }
- { src: "{{ fabio_tls_src_dir}}/{{ fabio_tls_server_cert }}", dest: "{{ fabio_tls_dest_dir }}/{{ fabio_tls_server_cert }}" }
- { src: "{{ fabio_tls_src_dir}}/{{ fabio_tls_server_key }}", dest: "{{ fabio_tls_dest_dir }}/{{ fabio_tls_server_key }}" }
