---
- hosts: mongo
  pre_tasks:
  - name: check apt key
    apt_key:
      url: "{{ item.url }}"
      id: "{{ item.id }}"
      state: present
    with_items:
    - { url: "https://www.mongodb.org/static/pgp/server-3.2.asc", id: EA312927 }
    - { url: "https://www.mongodb.org/static/pgp/server-3.6.asc", id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5 }
    - { url: "https://www.mongodb.org/static/pgp/server-3.4.asc", id: 0C49F3730359A14518585931BC711F9BA15703C6}
    become: True
  roles:
    - role: greendayonfire.mongodb
      become: True
      mongodb_version: "3.4"
      mongodb_repository:
        "3.2": "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
        "3.4": "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse"
        "3.6": "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse"
      mongodb_security_authorization: "enabled"
      mongodb_login_host: 192.168.56.23
      mongodb_net_bindip: 0.0.0.0
      mongodb_replication_replset: rs0
      mongodb_replication_params:
      - { host_name: 192.168.56.21, host_port: "{{ mongodb_net_port }}" }
      - { host_name: 192.168.56.22, host_port: "{{ mongodb_net_port }}" }
      - { host_name: 192.168.56.23, host_port: "{{ mongodb_net_port }}" }
