---
- hosts: controller
  roles:
  - role: local.pki
    pki_servers:
      - cname: consul.server1.localdomain
        include_localhost: True
        sans:
          - consul.server1.localdomain
        altips:
        - 192.168.56.21
      - cname: consul.server2.localdomain
        include_localhost: True
        sans:
          - consul.server2.localdomain
        altips:
        - 192.168.56.22
      - cname: consul.server3.localdomain
        include_localhost: True
        sans:
          - consul.server3.localdomain
        altips:
        - 192.168.56.23
      - cname: server.global.nomad
        sans:
          - nomad.service.consul
        include_localhost: True
        altips: "{{ groups['nomad_servers'] | map('extract', hostvars, 'ansible_host')|list}}"
      - cname: graylog.service.consul
        include_localhost: True
        altips: "{{ groups['graylog_servers'] | map('extract', hostvars, 'ansible_host')|list}}"
      - cname: client.global.nomad
        include_localhost: True
        altips: "{{ groups['nomad_nodes'] | map('extract', hostvars, 'ansible_host')|list}}"
      - cname: vault.service.consul
        include_localhost: True
        sans:
        - "*.vault.service.consul"
        altips: "{{ groups['vault_servers'] | map('extract', hostvars, 'ansible_host')|list}}"
      - cname: registry.service.consul
        include_localhost: True
        altips:
        - 192.168.56.21
        - 192.168.56.22
        - 192.168.56.23
      - cname: fabio.service.consul
        include_localhost: True
        sans:
        - "*.fabio.service.consul"
        - "*.nomad.cluster"
      - cname: ldap.service.consul
        sans:
        - "ldap0.service.consul"
        - "ldap1.service.consul"
        altips: "{{ groups['openldap-servers'] | map('extract', hostvars, 'ansible_host')|list}}"
      - cname: keycloak.service.consul
        sans:
        - "*.keycloak.service.consul"
        altips: "{{ groups['keycloak-servers'] | map('extract', hostvars, 'ansible_host')|list}}"
    pki_clients:
    - consul-worker1
    - consul-worker2
    - consul-worker3
    - consul-controller
  tasks:
  - name: install openjdk
    apt:
      name: openjdk-8-jdk
    tags: create_truststore
    become: True
  - name: import certificates into java keystore
    java_cert:
      cert_path: "{{item.cert_path}}"
      cert_alias: "{{item.cert_alias}}"
      keystore_path: /home/vagrant/pki/truststore.jks
      keystore_create: True
      keystore_pass: changeit
    with_items:
    - { cert_path: /home/vagrant/pki/ca.pem, cert_alias: 'default'}
    - { cert_path: /home/vagrant/pki/ldap.service.consul.pem, cert_alias: 'ldap'}
    tags: create_truststore
