- hosts: smtp-servers
  tasks:
  # TODO see angstwad. Need to decide if we check pre-requisites here, then we need some logic
  - name: ensure docker-py is installed
    pip:
      name: "{{item}}"
    with_items:
    - docker
    - python-consul
    become: True

  # mailslurper image only has a latest tag
  # TODO: provide custom mailslurper image
  - name: start mailslurper
    docker_container:
      image: rattermeyer/mailslurper:1.12.1
      name: mailslurper
      ports:
      - "8080:8080"
      - "8085:8085"
      - "2500:2500"
      restart_policy: always
    become: True

  - name: register service
    consul:
      service_name: smtp
      service_port: 2500
    become: True